# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mgorshkov/Work/matrix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mgorshkov/Work/matrix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/mgorshkov/Work/matrix/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mgorshkov/Work/matrix/CMakeFiles /home/mgorshkov/Work/matrix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mgorshkov/Work/matrix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matrix_test

# Build rule for target.
matrix_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_test
.PHONY : matrix_test

# fast build rule for target.
matrix_test/fast:
	$(MAKE) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/build
.PHONY : matrix_test/fast

#=============================================================================
# Target rules for targets named matrix

# Build rule for target.
matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix
.PHONY : matrix

# fast build rule for target.
matrix/fast:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/build
.PHONY : matrix/fast

#=============================================================================
# Target rules for targets named matrixlib

# Build rule for target.
matrixlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrixlib
.PHONY : matrixlib

# fast build rule for target.
matrixlib/fast:
	$(MAKE) -f CMakeFiles/matrixlib.dir/build.make CMakeFiles/matrixlib.dir/build
.PHONY : matrixlib/fast

matrix.o: matrix.cpp.o

.PHONY : matrix.o

# target to build an object file
matrix.cpp.o:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/matrix.cpp.o
.PHONY : matrix.cpp.o

matrix.i: matrix.cpp.i

.PHONY : matrix.i

# target to preprocess a source file
matrix.cpp.i:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/matrix.cpp.i
.PHONY : matrix.cpp.i

matrix.s: matrix.cpp.s

.PHONY : matrix.s

# target to generate assembly for a file
matrix.cpp.s:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/matrix.cpp.s
.PHONY : matrix.cpp.s

matrix_test.o: matrix_test.cpp.o

.PHONY : matrix_test.o

# target to build an object file
matrix_test.cpp.o:
	$(MAKE) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/matrix_test.cpp.o
.PHONY : matrix_test.cpp.o

matrix_test.i: matrix_test.cpp.i

.PHONY : matrix_test.i

# target to preprocess a source file
matrix_test.cpp.i:
	$(MAKE) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/matrix_test.cpp.i
.PHONY : matrix_test.cpp.i

matrix_test.s: matrix_test.cpp.s

.PHONY : matrix_test.s

# target to generate assembly for a file
matrix_test.cpp.s:
	$(MAKE) -f CMakeFiles/matrix_test.dir/build.make CMakeFiles/matrix_test.dir/matrix_test.cpp.s
.PHONY : matrix_test.cpp.s

matrixlib.o: matrixlib.cpp.o

.PHONY : matrixlib.o

# target to build an object file
matrixlib.cpp.o:
	$(MAKE) -f CMakeFiles/matrixlib.dir/build.make CMakeFiles/matrixlib.dir/matrixlib.cpp.o
.PHONY : matrixlib.cpp.o

matrixlib.i: matrixlib.cpp.i

.PHONY : matrixlib.i

# target to preprocess a source file
matrixlib.cpp.i:
	$(MAKE) -f CMakeFiles/matrixlib.dir/build.make CMakeFiles/matrixlib.dir/matrixlib.cpp.i
.PHONY : matrixlib.cpp.i

matrixlib.s: matrixlib.cpp.s

.PHONY : matrixlib.s

# target to generate assembly for a file
matrixlib.cpp.s:
	$(MAKE) -f CMakeFiles/matrixlib.dir/build.make CMakeFiles/matrixlib.dir/matrixlib.cpp.s
.PHONY : matrixlib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... package"
	@echo "... test"
	@echo "... matrix_test"
	@echo "... matrix"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... matrixlib"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... matrix_test.o"
	@echo "... matrix_test.i"
	@echo "... matrix_test.s"
	@echo "... matrixlib.o"
	@echo "... matrixlib.i"
	@echo "... matrixlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

